# Interpolation and Geostatistics {#interpolation}

Geostatistics is concerned with the modelling, prediction and
simulation of spatially continuous phenomena.  The typical problem
is a missing value problem: we observe a property of a phenomenon
$Z(s)$ at a limited number of sample locations $s_i, i = 1,...,n$,
and are interested in the property value at all locations $s_0$,
so we have to predict it for unobserved locations. This is also
called _kriging_, or Gaussian process prediction.  In case
$Z(s)$ contains a white noise component $\epsilon$, as in
$Z(s)=S(s)+\epsilon(s)$, an alternative but similar goal is to
predict $S(s)$, which may be called filtering or smoothing.

In this chapter we will show simple approaches for handling
geostatistical data, will demonstrate simple interpolation methods,
explore modelling spatial correlation, spatial prediction and
simulation. We will use package `gstat` [@R-gstat, @gstatcg],
which offers a fairly wide palette of models and options for
geostatistical analysis.
